trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  projectName: <%= fullName %>
  appFolder: ''
  DEPLOY_VERSION: '$(Build.BuildId)'
  StorageAccountName: 'storagecp1234'
  npm_config_cache: '$(Pipeline.Workspace)/.npm'
  FolderPrefix: '$(Build.SourceBranchName)'

stages:
  - stage: CI
    displayName: 'Continuous Integration'
    jobs:
      - job: Build
        steps:
          - checkout: self
            persistCredentials: true
          - task: NpmAuthenticate@0
            displayName: 'Npm authentication'
            inputs:
              workingFile: '.npmrc'
          - task: CmdLine@2
            displayName: Checkout $(System.PullRequest.SourceBranch)
            inputs:
              script: |
                source=$(System.PullRequest.SourceBranch)
                git checkout ${source#"refs/heads/"}
                git update-index --assume-unchanged .npmrc
                git config --global receive.advertisePushOptions true
                git config --global user.email "email@hdn.digital"
                git config --global user.name "Yout Name"
          - template: ../templates/pr-build-template.yml
            parameters:
              steps:
                - script: |
                    (yarn install)
                  displayName: 'Install dependencies'
                - script: |
                    (yarn run coverage)
                  displayName: 'Unit tests'
                - script: |
                    (yarn build)
                  displayName: 'Build packages'
                - script: |
                    (yarn new-version:test)
                  displayName: 'Generate versions'

  - stage: CD
    displayName: 'Continuous Delivery'
    jobs:
      - job: Publish
        steps:
          - task: CmdLine@2
            displayName: Install yarn ci package
            inputs:
              script: yarn ci

          - task: CmdLine@2
            displayName: Build Storybook
            inputs:
              script: yarn build-storybook
